### ISSUE TITLE
Add kevmoo as a contributor

### ISSUE THREAD

**Issue by kevmoo** [google/webkit_inspection_protocol.dart#43]
I'll help configure travis for weekly cron, etc

**Comment by kevmoo** [comment]
CC @devoncarew

**Comment by devoncarew** [comment]
Happy to add you. If we're taking this as an official dep of some core functionality, we can also move it into dart-lang.

**Comment by devoncarew** [comment]
done

**Comment by kevmoo** [comment]
We're not. I am adding it to some package health tracking tools (repo
manager) so we can keep an eye on it.
