### ISSUE TITLE
Incorrect field is accessed to get scope name in WipScope.scope

### ISSUE THREAD

**Issue by annagrin** [google/webkit_inspection_protocol.dart#49]
https://github.com/google/webkit_inspection_protocol.dart/blob/26490691180836cdbb050f1934a4a9621962d54a/lib/src/debugger.dart#L163

This should be 

` String get scope => _map['type'] as String; `

**Comment by devoncarew** [comment]
Ah, good catch. PRs welcome :)

**Comment by annagrin** [comment]
Sure, will do!
