### ISSUE TITLE
Report reason for exit and errors in web connection

### ISSUE THREAD

**Issue by annagrin** [google/webkit_inspection_protocol.dart#86]
Original issue: https://github.com/flutter/flutter/issues/99157

We are seeing some web connections closing right after the start of debugging with no error messages (see the verbose logs in the issue above). 

**Would it be possible to** 
- add `onError` handler to the web socket the web connection is using, and report those errors to the caller (maybe the  error handler can be passed to the constructor):

https://github.com/google/webkit_inspection_protocol.dart/blob/c34ebda31d11c8e6e4c429ca2fbd979c9310c311/lib/webkit_inspection_protocol.dart#L169

- report the reason for exiting?

**dwds caller**
dwds just stops debugging when the connection is closed, and is not aware of the reason:

https://github.com/dart-lang/webdev/blob/8c814f9d89915418d8abe354ff9befec8f2906b2/dwds/lib/src/handlers/dev_handler.dart#L241
https://github.com/dart-lang/webdev/blob/8c814f9d89915418d8abe354ff9befec8f2906b2/dwds/lib/src/handlers/dev_handler.dart#L527

**Comment by annagrin** [comment]
@devoncarew I see this issue is closed as completed but it is not clear to me what the changes were... Is there a way to pass an error handler to the created socket connection? Maybe an `onError` parameter could be aded to https://github.com/google/webkit_inspection_protocol.dart/blob/57ebca4b97310a10774c59c0fb056d8f23bd5cee/lib/webkit_inspection_protocol.dart#L219

**Comment by devoncarew** [comment]
I believe it was closed as a result of https://github.com/google/webkit_inspection_protocol.dart/pull/88; I'm 100% that addresses all of this issue however (or whether that work was rolled into flutter?).

**Comment by annagrin** [comment]
The https://github.com/google/webkit_inspection_protocol.dart/pull/88 allows retries on connection to chrome tab, the current issue is asking for error handling if such a connection stops working for any reasons so the caller (dwds) can report it in the logs. The original issue is in flutter, it seems that the connection just stops working and we cannot get the error and the stacktrace.

**Comment by devoncarew** [comment]
Sorry, above I meant to say 'not 100% sure'!

Yes, we can augment the API here in order to better pass errors through.

Let me take a look at the API here. I'm not sure whether we want an `onError` error handler parameter, or just to pass failures back through the returned `Future`s.

**Comment by devoncarew** [comment]
Address in #92 and published as 1.2.0.
